#!/bin/bash
java -Xmx500M -cp "/usr/local/lib/antlr-4.5-complete.jar:$CLASSPATH" org.antlr.v4.Tool Src2.g4 && javac Src2*.java && javac Compiler2*.java && java Compiler2 sample.src > sample.j && java -jar jasmin.jar sample.j && java sample
